[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1
restartLimit = 3

[deploy.envs]
NODE_ENV = "production"

[build.env]
NODE_VERSION = "20.x"
NPM_VERSION = "10.x"

[build.cache]
enabled = true
paths = ["node_modules"]
