[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production"

# Specify Node.js version
[build.env]
NODE_VERSION = "20.x"